### ISSUE TITLE
Клонировать репо и скомпилировать код

### ISSUE THREAD

**Issue by tmshv** [tmshv/game#2]
- установить клиент
- клонировать репозиторий на компьютер
- настроить воркспейс
- скомпилировать код

**Comment by tmbo91** [comment]
чей клиент установить?

**Comment by tmshv** [comment]
снизу страницы в меню Clients. Тебе для Винды

**Comment by tmbo91** [comment]
а какая директория этого репозитория?

**Comment by tmbo91** [comment]
всё, настраиваю рабочее место

**Comment by tmshv** [comment]
У себя храни где хочешь. Рекомендую там, где не используется кирилица в пути.
Например, C:\Dev, C:\Workspace и т. д.

Под настройкой рабочего места я имел ввиду настройку редактора, чтобы можно было уже запускать код.
Для Сублима найди плагин Package Control и установи поддержку Action Script 3

**Comment by tmbo91** [comment]
слушай, я поставил package control и установил поддержку action script, но
1)там не было цифры 3
2)после запуска нового текстового файла поддержка пропадает

**Comment by tmshv** [comment]
Он поддерживает много языков, поэтому надо сказать ему какой у тебя язык. Это делается либо автоматически по расширению as, либо меню Tools -> Command Palette (запомни шорткат): команда Set Syntax: Action Script 3

**Comment by tmbo91** [comment]
ну вот там цифры 3 нету

**Comment by tmshv** [comment]
![GitHub Logo](http://f.cl.ly/items/3E1D2V2I3x0s1V2Q1Z2R/subl1.png)
![GitHub Logo](http://f.cl.ly/items/420Y0p1c2D2D041F3P1h/subl2.png)

**Comment by tmshv** [comment]
Лол у меня пока не получилось запустить что-нибудь через Сублим.

**Comment by tmshv** [comment]
FlashDevelop будет работать без проблем

**Comment by tmshv** [comment]
http://clock.co.uk/tech-blogs/compiling-actionscript-30-with-sublime-text-2

**Comment by tmshv** [comment]
Все таки получилось на Сублиме сделать что-нибудь.
